# Generated by Django 4.2.11 on 2024-04-29 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_produced', models.DateField(verbose_name='Production Date')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_creators', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_updaters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Chemical Name')),
            ],
        ),
        migrations.CreateModel(
            name='ReagentContainer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('container_number', models.IntegerField(blank=True, default=0, null=True, verbose_name='Container number')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Volume (liters)')),
                ('production', models.BooleanField(verbose_name='Production')),
                ('approved', models.BooleanField(blank=True, null=True, verbose_name='Approved')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod_app.batch', verbose_name='Related Batch')),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod_app.chemical', verbose_name='Chemical')),
            ],
        ),
    ]
