# Generated by Django 4.2.11 on 2024-04-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reagentcontainer',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='reagentcontainer',
            name='production',
        ),
        migrations.AddField(
            model_name='reagentcontainer',
            name='is_recyclable',
            field=models.BooleanField(default=False, verbose_name='Recyclable'),
        ),
        migrations.AddField(
            model_name='reagentcontainer',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='reagentcontainer',
            name='purity_level',
            field=models.IntegerField(default=0, verbose_name='Purity Level (%)'),
        ),
        migrations.AddField(
            model_name='reagentcontainer',
            name='storage_condition',
            field=models.CharField(choices=[('ambient', 'Ambient'), ('refrigerated', 'Refrigerated'), ('frozen', 'Frozen')], default='ambient', max_length=50, verbose_name='Storage Condition'),
        ),
    ]
